package com.cloudaxis.agsc.portal.constants;

public class CandidateProfileConstants {

	// Excel suffix
	public static final String EXCEL_SUFFIX = "xls"; 
	
	// default file name
	public static final String DEFALUT_FILE_NAME = "candidate-profile";
	
	// default sheet name
	public static final String DEFALUT_SHEET_NAME = "candidate-profile";
		
	// empty display
	public static final String EMPTY_DISPLAY = "--";
	
	// header array
	public static final String[] EXCEL_HEADERS = {
			"APPLICANT",
			"EMAIL",
			"PHONE",
			"THE JOB OPPORTUNITIES WE ARE CURRENTLY OFFERING CONCERN ONLY LIVE AT HOME CAREGIVING - THIS MEANS THAT YOU WILL HAVE TO LIVE AT THE HOME OF YOUR CLIENT, WHICH IS VERY COMMON, WELL REGULATED, AND SAFE IN SINGAPORE. THIS IS NOT A HOSPITAL JOB --- YOU WILL NOT BE ABLE TO BRING YOUR FAMILY TO SINGAPORE ***ARE YOU INTERESTED IN THIS JOB ??***",
			"WE ARE CURRENTLY OFFERING LIVE-IN CAREGIVER OPPORTUNITIES BOTH IN HONG KONG AND SINGAPORE. YOU CAN APPLY TO BOTH LOCATIONS TO MAXIMIZE YOUR CHANCES OF GETTING A PLACEMENT QUICKLY. PLEASE TICK ALL LOCATIONS THAT INTEREST YOU",
			"WORK IN SG",
			"WORK IN HK",
			"WORK IN TW",
			"PLEASE GIVE US YOUR SKYPE ID IF YOU HAVE ONE ALREADY.",
			"WHAT IS YOUR GENDER?",
			"WHAT IS YOUR DATE OF BIRTH?",
			"WHAT IS YOUR PLACE OF BIRTH?",
			/** -----  newly added ------- */
			"AGE",
			"DATE APPLIED",
			"DATE OF PLACEMENT",
			"NUMBER OF PLACEMENTS",
			"STATUS",
			"REGISTERED WITH CONCORDE",
			"ADVANCED PLACEMENT SCHEME",
			"MEDICAL CERT VERIFIED",
			"FOR HOW LONG WOULD YOU LIKE TO WORK AS A LIVE-IN CAREGIVER WITH ACTIVE GLOBAL?",
			/** ------   end  -------- */
			"WHAT IS THE AIRPORT NEAREST TO YOUR HOME TOWN?",
			"WHAT IS YOUR COUNTRY OF CITIZENSHIP?",
			"WHAT IS YOUR CURRENT RESIDENTIAL ADDRESS?",
			"WHAT IS YOUR HEIGHT IN CENTIMETERS. PLEASE JUST ENTER NUMERICAL VALUE, EG: 168",
			"WHAT IS YOUR WEIGHT IN KG? PLEASE JUST ENTER NUMERICAL VALUE, E.G.: 57",
			"WHAT IS YOUR MARITAL STATUS",
			"DO YOU HAVE CHILDREN AND HOW MANY?",
			"IF YOU HAVE CHILDREN, PLEASE LIST THEIR NAMES & AGES",
			"HOW MANY SIBLINGS TO YOU HAVE? (EXAMPLE: 1 BROTHER AND 2 SISTERS)",
			"WHICH LANGUAGES DO YOU SPEAK? (PLEASE TICK ALL THAT APPLY)",
			"WHAT IS YOUR RELIGION?",
			"DO YOU FOLLOW A SPECIFIC DIET?",
			"ARE YOU CURRENTLY HOLDING A PASSPORT?",
			"WHICH NURSING SCHOOL DID YOU GO TO? (NAME OF SCHOOL AND CITY)",
			"YEAR OF GRADUATION",
			"NUMBER OF YEARS OF STUDIES",
			"WHAT NURSING DEGREE / DIPLOMA DID YOU OBTAIN?",
			"HOW MANY YEARS OF RELEVANT EXPERIENCE DO YOU HAVE (RELEVANT EXPERIENCE MEANS: WORKING IN A HOSPITAL, CLINIC, NURSING HOME, HOME CARE, WHILE CARING FOR ELDERLY OR SICK PATIENTS)",
			"ARE YOU CERTIFIED FOR CPR / FIRST AID?",
			"HAVE YOU WORKED AS A CAREGIVER BEFORE?, IF YES, GIVE DETAILS (WHERE, WHEN, ETC.)",
			"HAVE YOU WORKED IN SINGAPORE BEFORE?",
			"IF YOU WORKED IN SINGAPORE BEFORE, KINDLY PROVIDE US MORE DETAILS ON WHEN, POSITION, WORK PERMIT OR PASS THAT WAS USED AND YOUR WORK PERMIT OR FIN NUMBER. *",
			"CURRENT EMPLOYER / CITY",
			"PLEASE LET US KNOW IF YOU HAVE EXPERIENCE IN THE FOLLOWING AREAS (TICK ALL BOXES WHERE YOU HAVE AT LEAST SOME EXPERIENCE):",
			"CURRENT ROLE / JOB",
			"FOR HOW LONG HAVE YOU BEEN IN THIS JOB?",
			"WHAT IS YOUR MAIN MOTIVATION TO BECOME A LIVE-IN CAREGIVER?",
//			"FOR HOW LONG WOULD YOU LIKE TO WORK AS A LIVE-IN CAREGIVER WITH ACTIVE GLOBAL?",
			"ASSUMING WE OFFER YOU A JOB, AND WE HAVE ALREADY SECURED A VISA/WORKED PERMIT FOR YOU, HOW SOON CAN YOU COME TO SINGAPORE? PLEASE BE TRUTHFUL AND REALISTIC, DEPENDING ON YOUR CURRENT NOTICE FOR RESIGNATION AND PERSONAL COMMITMENTS. PLEASE NOTE THAT MOST OF OUR CLIENTS ARE IN A RUSH TO GET A CAREGIVER AND ARE NOT READY TO WAIT A MONTH FOR YOU. AT THE SAME TIME, IF YOU COMMIT TO A CERTAIN AVAILABILITY IT MEANS YOU ARE ABLE TO COME IN THIS TIMEFRAME. THIS IS IMPORTANT.",
			"IF YOU HAVE ANY ALLERGIES, PLEASE STATE WHICH ONE(S)",
			"DO YOU HAVE OR WERE YOU EVER DIAGNOSED WITH ANY OF THE FOLLOWING CONDITIONS? PLEASE CHECK THE CORRESPONDING BOXES.",
			"IF YOU CHECKED ANY OF THE BOXES, PLEASE PROVIDE SOME INFORMATION ABOUT THE TREATMENT/ MEDICATION YOU USE(D). *** PLEASE NOTE THAT LIES OR OMISSIONS ABOUT YOUR MEDICAL HISTORY ARE A VERY SEVERE OFFENSE IN SINGAPORE, AND WILL NOT BE TOLERATED ***",
			"WHAT ARE YOUR HOBBIES (WHAT DO YOU LIKE TO DO WHEN YOU ARE NOT WORKING)?",
			"FOR FILIPINO CAREGIVERS ONLY: HAVE YOU OBTAINED TESDA NCII CERTIFICATION?",
			"PLEASE GIVE US THE BEST DAYS / TIMES TO SCHEDULE AN INTERVIEW WITH YOU (EG: \"TUESDAYS AND WEDNESDAY MORNINGS\")",
			"IF YOU WERE REFERRED BY A FRIEND, PLEASE LET US KNOW HIS / HER NAME AND EMAIL ADDRESS !",
			"DOC Registered with Concorde",
			"DOC Advanced Placement Scheme",
			"DOC Medical Cert Verified",
			"DOC 1 - New Applicant",
			"DOC 2 - Awaiting Documents",
			"DOC 3 - Scheduling Interview",
			"DOC 4 - Interview Scheduled",
			"DOC 5 - Shortlisted",
			"DOC 6 - Not Selected/Not Interested for now",
			"DOC 7 - Shortlisted with differed availability",
			"DOC 8 - Ready for Placement",
			"DOC 9 - Tagged",
			"DOC 10 - Contracted",
			"DOC 11 - On Hold",
			"DOC 12 - Blacklisted",
			"PLEASE UPLOAD YOUR PASSPORT",
			"PLEASE UPLOAD YOUR DEGREES AND CERTIFICATES HERE (AS PDF)",
			"PLEASE UPLOAD YOUR DEGREES AND CERTIFICATES HERE (AS PDF) - UPLOAD HERE ONLY IF YOU HAVE MORE THAN 1 DEGREE / CERTIFICATE",
			"PLEASE UPLOAD YOUR DEGREES AND CERTIFICATES HERE (AS PDF) - UPLOAD HERE ONLY IF YOU HAVE MORE THAN 2 DEGREE / CERTIFICATE",
			"PLEASE KINDLY ATTACH A NICE, SMILING PICTURE OF YOU, SO WE KNOW WHO WE ARE TALKING TO WHEN WE CALL YOU ! (PDF FORMAT ONLY PLEASE)",
			"OTHER RELEVANT FILE UPLOAD (1)",
			"OTHER RELEVANT FILE UPLOAD (2)",
			"OTHER RELEVANT FILE UPLOAD (3)",
			"OTHER RELEVANT FILE UPLOAD (4)",
	}; 
}
